name: '[ADR] Draft Architecture Decision Record'
description: 'Issues for draft ADRs on which is worked on before they are being pushed via PR to the "proposed" state.'
title: '[Draft ADR] <ADR Title>'
labels: [adr]
assignees: 
- ddneves
  
body:
  - type: markdown
    attributes:
      value: |
        ## Required information
  - type: input
    id: context
    attributes:
      label: Context
      description: Please provide us some context.
    validations:
      required: false
  - type: input
    id: problem
    attributes:
      label: Problem Statement
      description: What are we trying to solve with this ADR? Why is it required?
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        After your proposal, the following [process](../../src/diagrams/ADR-000-Process.md) will be initiated.

